### ISSUE TITLE
这个统计礼物数量吗？

### ISSUE THREAD

**Issue by consciousgaze** [Crawler995/DouyuBarrage-Pro#3]
请问这个能统计房间里受到了多少礼物吗？

而后可以发弹幕吗？

**Comment by Crawler995** [comment]
我没做这个功能，但是是可以做到的
[这里](https://github.com/Crawler995/DouyuBarrage-Pro/blob/master/dybarrage-server/src/websocket/crawler/RawMessageHandler.ts)第52行的函数里面可以看到我过滤了除了chatmsg之外的消息，你可以改一下，[斗鱼开放文档](https://pan.baidu.com/share/init?surl=CAyrMMS6XWoc95ORf9-Pqw)里面有相关数据格式（提取码ezoj）
发弹幕也是一样的道理，参照斗鱼文档，把你想发的消息使用上面那个文件中的encode函数编码后send就行了

**Comment by Crawler995** [comment]
@consciousgaze 如上

**Comment by consciousgaze** [comment]
监控type是bgd信息得不到全部的礼物消息。办卡以下的好像看不到。你知道怎么能看全吗？

**Comment by Crawler995** [comment]
@consciousgaze 我没研究过 这个你得仔细去分析斗鱼的协议了 你可以试着抓包啊什么的
