### ISSUE TITLE
抖音、快手平台的弹幕抓取

### ISSUE THREAD

**Issue by w4mxl** [Crawler995/DouyuBarrage-Pro#5]
请问能否在你的这个斗鱼平台基础上扩展支持抖音、快手平台呢？

**Comment by Crawler995** [comment]
@w4mxl 理论上来说可以 但是可能需要做一些改动 比如数据库的表设计 爬虫模块等等 当初设计的时候也没想到扩展平台 所以扩展有一定困难 有兴趣的话你可以试试 有不懂的可以继续问我

**Comment by w4mxl** [comment]
> @w4mxl 理论上来说可以 但是可能需要做一些改动 比如数据库的表设计 爬虫模块等等 当初设计的时候也没想到扩展平台 所以扩展有一定困难 有兴趣的话你可以试试 有不懂的可以继续问我

嗯，谢谢。不过我对爬虫实现技术这块不太懂的 😂
