### ISSUE TITLE
在服务器上运行server与web程序，请求返回 Invalid Host Header

### ISSUE THREAD

**Issue by cheerryio** [Crawler995/DouyuBarrage-Pro#6]
经过检索，这可能是webpack中disableHostCheck参数设置为false. 导致前端只能接受127.0.0.1或者localhost本地请求。
  如果用服务器IP或者域名请求，返回Invalid Host Header. 但是由于我对webpack和react本身的不熟悉，我也不能清晰定位配置文件位置和参数位置，无法正确配置。

**Comment by Crawler995** [comment]
@cheerryio 目前我是这样设置的：客户端使用React自带的跨域功能（即package.json中应该有个proxy字段），那个proxy字段应该设置的是localhost:3001，也就是客户端运行在localhost:3000去跨localhost:3001（也就是服务器地址），我觉得或许与这个有关。你把server放服务器上了，客户端去跨localhost:3001的域就找不到服务器了。
如果需要将server运行在服务器上，可以将客户端打包放在server的资源路径下面然后加点代码，这样就像访问普通网页一样，输入域名即可打开管理中心，也可以顺便避免跨域问题。

**Comment by cheerryio** [comment]
我已经将web中package.json的proxy字段改为 http://我的域名:3001。并将web中所有出现localhost:3000的地方更改为 我的域名:3000，以便能够正常利用跳转网页。将web中为了与后端进行连接的websocket连接地址改为了 我的域名:3001。 现在进入主界面，下方卡片一直在旋转加载。进入房间，显示服务器连接成功，但是主播信息的component一直在旋转加载。我也并不能找到在哪里可以控制开始抓取弹幕和停止抓取弹幕。
![QQ截图20200623151855](https://user-images.githubusercontent.com/50071687/85372796-f4677780-b564-11ea-8bfa-d951d285fc8f.png)
![QQ图片20200623151834](https://user-images.githubusercontent.com/50071687/85372799-f5000e00-b564-11ea-8923-df348f9070ad.png)

**Comment by Crawler995** [comment]
@cheerryio 你懂浏览器控制台吗？你可以看看网络请求，看具体的问题是啥，是404还是服务端报错等等。这个暴露的问题是http接口出问题了，所以加载不出来主播基本情况。

**Comment by cheerryio** [comment]
我的所有网络请求并没有出现404或者502（包括ALL中和XHR中的所有请求）。具体情况你可以访问一下 www.baobao.pink:5000 查看一下。（并且我发现点开某些XHR的请求连接，都会跳到 / 这个路径下的页面

**Comment by Crawler995** [comment]
@cheerryio 我觉得是你后来加在服务器里面的路由代码出问题了 /api的请求返回的是html页面 本来是应该返回json数据的 你检查一下

**Comment by dfaofeng** [comment]
这是前端没连上后端吧，f12看下控制台那个api报错

**Comment by cheerryio** [comment]
通过在package.json设置proxy字段实现对/api的匹配代理只有在Development Mode下有效。所有只有直接写上 ajax的请求路径 http://域名:3001/api........那么就要自己解决这个跨域问题了。。
令，能不能实现即使断开socket连接爬取也不停止的版本~~~~
感谢开源，我将关闭这个Issue。
